version: '3.8'

services:
  # Service MariaDB (base de données)
  data:
    image: mariadb:latest
    container_name: DATA
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=data
      - MARIADB_USER=monuser
      - MARIADB_PASSWORD=password
    volumes:
      - ./etape-2/create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - TP3
    ports:
      - "3306:3306"  # Optionnel, expose le port pour accéder à la base de données depuis l'hôte

  # Service PHP (avec PHP-FPM)
  script:
    build:
      context: ./php  # Ce dossier doit contenir le Dockerfile
    container_name: SCRIPT
    volumes:
      - ./etape-1:/app
    networks:
      - TP3
    depends_on:
      - data

  # Service NGINX
  http:
    image: nginx:latest
    container_name: HTTP
    volumes:
      - ./etape-1/index.php:/app/index.php
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - TP3
    depends_on:
      - script

networks:
  TP3:
    driver: bridge

